name: Update diagram

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

env:
  TRIGGER_JOB: false

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch and set default branch
        run: |
          git fetch origin

      - name: Check for added or deleted files
        run: |
          files=$(git show --name-status --diff-filter=AD)
          if [ -n files ]; then
            echo "TRIGGER_JOB=true" >> $GITHUB_ENV
            echo "Files deleted or added !" >> $GITHUB_STEP_SUMMARY
          fi

  diagram:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        if: ${{ env.TRIGGER_JOB == 'true' }}
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
