name: Update diagram

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for added or deleted files
        run: |
          files=$(git diff --diff-filter=AD HEAD^ HEAD)
          if [ -n files ]; then
            echo "TRIGGER_JOB=true" >> $GITHUB_ENV
          fi

  diagram:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        if: ${{ needs.check_changes.outputs.trigger_job == 'true' }}
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
