name: Update diagram

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  check_new_or_deleted_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new or deleted files
        run: |
          git fetch origin ${{ github.base_ref }}
          if ${{ github.event_name == 'pull_request' }}; then
              echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_ENV
          else
              echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_ENV
          fi


  get_data:
    needs: check_new_or_deleted_files
    runs-on: ubuntu-latest
    if: ${{ env.TRIGGER_GET_DATA == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
