name: Update diagram

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

env:
  TRIGGER_JOB: false

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for added or deleted files
        run: |
          git diff --diff-filter=AD HEAD^ HEAD > /dev/null
          if [ $? -eq 0 ]; then
            echo "TRIGGER_JOB=true" >> $GITHUB_ENV
          fi

  diagram:
    needs: check_changes
    if: ${{ env.TRIGGER_JOB == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
